package mongo

import "github.com/dembygenesis/blog_exam/pkg/models_autogenerated"

//
// Theoretical application if mongo db is used
//

type Article struct {
	
}

func (a *Article) Create() error {
	return nil
}

func (a *Article) Read(id int) (*models_autogenerated.ArticleSlice, error) {
	return nil, nil
}


