package mongo

import (
	"github.com/dembygenesis/blog_exam/pkg/models"
	"github.com/dembygenesis/blog_exam/pkg/models_autogenerated"
)

//
// Implement mongo methods here in the future
//

func (a *Article) Create(entry models.Article) (*models.ArticleId, error) {
	return nil, nil
}

func (a *Article) Read(id int) (*models_autogenerated.ArticleSlice, error) {
	return nil, nil
}