package logic

import (
	"github.com/dembygenesis/blog_exam/pkg/models"
	"github.com/dembygenesis/blog_exam/pkg/models_autogenerated"
)

func (h *Handler) Create(article models.Article) (*models.ArticleId, error) {
	return nil, nil
}

func (h *Handler) Read(id int) (*models_autogenerated.ArticleSlice, error) {
	return h.store.Read(id)
}