package store

import (
	"github.com/dembygenesis/blog_exam/pkg/models"
	"github.com/dembygenesis/blog_exam/pkg/models_autogenerated"
)

// Store has our app methods
type Store interface {
	AdminStore
}

// AdminStore contains our
type AdminStore interface {
	Create(article models.Article) (*models.ArticleId, error)
	Read(id int) (*models_autogenerated.ArticleSlice, error)
}