package store

import "github.com/dembygenesis/blog_exam/pkg/models_autogenerated"

// Store has our app methods
type Store interface {
	AdminStore
}

// AdminStore contains our
type AdminStore interface {
	Create() error
	Read(id int) (*models_autogenerated.ArticleSlice, error)
}