package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/dembygenesis/blog_exam/pkg/config"
	"github.com/dembygenesis/blog_exam/pkg/models"
	"github.com/dembygenesis/blog_exam/pkg/models_autogenerated"
	_ "github.com/go-sql-driver/mysql"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"time"
)

type Article struct {
	conn *sql.DB
}

const DbConnectTimeoutSecs int = 15
const DbExecTimeoutSecs int = 15

// NewMySQLStore returns a new Article MYSQL store instance
func NewMySQLStore(cfg *config.Database) (*Article, error) {
	// Setup connection
	if cfg == nil {
		return nil, fmt.Errorf("missing database cfg parameter")
	}
	str := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?charset=utf8&parseTime=true&timeout=%ds",
		cfg.User,
		cfg.Pass,
		cfg.Host,
		cfg.Port,
		cfg.Schema,
		DbConnectTimeoutSecs)
	db, err := sql.Open("mysql", str)
	if err != nil {
		return nil, fmt.Errorf("error establishing a connection: %v", err.Error())
	}
	db.SetConnMaxLifetime(time.Second * time.Duration(DbExecTimeoutSecs))

	return &Article{conn: db}, nil
}

func (a *Article) Create(article models.Article) (*models.ArticleId, error) {
	return nil, nil
}


func getReadFiler(id int) qm.QueryMod {
	if id != 0 {
		fmt.Println("Not 0", id)
		return qm.Where("id = ?", id)
	}
	return qm.Where("true")
}


func (a *Article) Read(id int) (*models_autogenerated.ArticleSlice, error) {
	boilCtx := boil.WithDebug(context.Background(), true)
	articles, err := models_autogenerated.Articles(getReadFiler(id)).All(boilCtx, a.conn)
	if err != nil {
		return nil, err
	}
	if len(articles) == 0 {
		return &models_autogenerated.ArticleSlice{}, nil
	}
	return &articles, nil
}
